name: NoMoreCreepers
version: v0.4
main: dansplugins.nomorecreepers.NoMoreCreepers
api-version: 1.13

commands:
  nomorecreepers:
  nmc:

permissions:
  nmc.help:
    default: true
  nmc.config:
    default: op